languageCode: en
title: Flowbite Application UI
baseURL: http://localhost:1313
enableInlineShortcodes: true
canonifyURLs: true
params:
  authors: Themesberg
  social_image_path: /application-ui/demo/images/og-image.jpg
markup:
  goldmark:
    renderer:
      unsafe: true
  highlight:
    noClasses: false
    style: colorful
  tableOfContents:
    startLevel: 2
    endLevel: 6
buildDrafts: true
buildFuture: true
enableRobotsTXT: true
metaDataFormat: yaml
disableKinds:
  - '404'
  - taxonomy
  - taxonomyTerm
  - RSS
publishDir: _gh_pages
